name: arsa

services:
  frontend:
    hostname: 'arsa-frontend'
    image: ghcr.io/gruppe-adler/arsa-frontend:main
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    networks:
      - arsa

  backend:
    hostname: 'arsa-backend'
    image: docker.io/library/arsa-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - arsa
    volumes:
      - arsa-db-volume:/app/db
      - arsa-servers-volume:/ars/servers
      - arsa-repo-volume:/ars/repo
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  arsa-db-volume:
  arsa-servers-volume:
  arsa-repo-volume:

networks:
  arsa:
    internal: true